name: GhostRealms
version: 0.0.1-alfa
author: Ghost Realms Network
main: net.ghostrealms.server.BackendClient
commands:
  plugins:
    aliases: [pl, plugins]
    description: View the server's plugin list